# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcd9f60d1851de3812acd6353d2a6d9481f34f67512f2664d9f7835b1065321824a67c89704c41233a87a049634efd3b27ba465bb10ed85c74e6197de0cfb69a

test:
  secret_key_base: ea7e441ad60393b570a08e06d4d7ebf929dc896401a2cf1f1306eaf1239b48fe0c9f026201fb7ddb3194f756fe14245953871f5614a39a908399d663b84c5bfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
